### ISSUE TITLE
vuex辅助函数取不到数据

### ISSUE THREAD

**Issue by lxzggaa** [thundernet8/common-mpvue#1]
//main.js
import {WrapPage} from 'common-mpvue'
import App from './index'

new WrapPage(App, {
  state: {
    wx: 'a'
  }
})

//index.vue
  import {mapState} from 'vuex'

  export default {
    computed: {
      ...mapState(['wx'])
    }
  }

取不到state的数据

**Comment by thundernet8** [comment]
@ChildLee 
这个WrapPage的state，实际上是是以模块形式注册的，模块名就是当前page的name，比如Index，那么state应该取Index.wx, 在page内部，你可以`this.$store.Index.wx`或者`this.$state.wx`来取wx的值，如果要mapState，可以尝试`mapState(['Index.wx'])`

**Comment by lxzggaa** [comment]
@thundernet8 
解决了,谢谢
